# Generated by Django 5.0.2 on 2024-03-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0002_exercise_workout_workoutexercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='body_part',
            field=models.CharField(choices=[('Forearms', 'Forearms'), ('Triceps', 'Triceps'), ('Biceps', 'Biceps'), ('Neck', 'Neck'), ('Shoulders', 'Shoulders'), ('Chest', 'Chest'), ('Back', 'Back'), ('Core', 'Core'), ('Upper Legs', 'Upper Legs'), ('Glutes', 'Glutes'), ('Calves', 'Calves'), ('Full Body', 'Full Body'), ('Other', 'Other')], max_length=16),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('Barbell', 'Barbell'), ('Dumbbell', 'Dumbbell'), ('Machine', 'Machine'), ('Bodyweight', 'Bodyweight'), ('Bands', 'Bands'), ('Cardio', 'Cardio'), ('Other', 'Other')], max_length=16),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Finished', 'Finished'), ('Template', 'Template')], default='Started', max_length=16),
        ),
    ]
