# Generated by Django 5.0.2 on 2024-03-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0003_alter_exercise_body_part_alter_exercise_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
