# Generated by Django 5.0.2 on 2024-03-05 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0004_alter_workout_created_at_alter_workout_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
