# Generated by Django 5.0.2 on 2024-03-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0005_alter_workout_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercisedetail',
            name='reps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutexercisedetail',
            name='sets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutexercisedetail',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
